### PR TITLE
Fix missing frames at rendering lags

### LINKED ISSUE #7: Recordings at wrong speed
While testing how well this plug-in can be integrated into one of my processes, I've discovered the recordings it produces are notably shorter than the primary recording. More specifically, they seem to be half the length and when playing them in VLC, they appear to run at double speed.

My use-case for these tests is to have a total of four recordings:

- Game recording OBS normally captures
- Overlay 1 (heart-rate monitor)
- Overlay 2 (gaze tracker)
- Composite (Game with both overlays applied)

I have tested twice now and both times the plug-in videos were shorter, though I only looked at the videos from the second test to observe the speed issue.
Here is the relevant OBS log file: [2021-05-25 14-31-14.txt](https://github.com/exeldro/obs-source-record/files/6542061/2021-05-25.14-31-14.txt)

The plug-in videos also lack audio. I have not done any special configuration for their audio, just the audio. Though still a bug, this is not an issue for me as the main recording has all the audio I need.

Definitely looking forward to this issue being fixed, as it would be very nice to record in a single instance of OBS than three and to have a version of the video with the overlays applied.

### LINKED ISSUE #33: Video and audio are out of sync
Hi,

I'm using this plugin to record my cam and game separately. Audio wasn't recording without manual setup, cause of #32 I guess.
I'm using nvenc, cause of #1.

Audio on both recordings are out of sync. The audio is delayed. The recording needs to be long enough to get out of sync, like an hour. I first thought it must have something to do with #7, but the fps and lengths of my files are correct. The audio seems to be cut off at the end.

(Ignore CQP, that's not the value I'm using)
grafik
grafik

### PR DESCRIPTION
**Pull request by norihiro**
### Description

The call back `source_record_filter_tick` counts the number of frames that passed from the previous frame.
The counter is sent through the 3rd argument of `video_output_lock_frame` so that the missing frames will be compensated.

Also fixed some warning messages reported by GCC.

### Motivation and Context

When rendering lags happen, frames are dropped and video and audio get misaligned.

This PR might fix #33, which reported the audio is lagged. What this PR trying to fix is an issue that the video is led instead.
It will also fix #7, which reported the recording becomes almost twice faster under 48.6% rendering lags.

### How Has This Been Tested?

1. Start OBS Studio with initial setup (scene collection and profile)
2. Add a V4L2 source for a camera, which is shooting a smart phone that plays an audio-sync-test video.
3. Add `Source Record` filter to the V4L2 source.
4. Add [`Rendering Lag`](https://github.com/norihiro/obs-rendering-lag) source to the same scene to inject rendering lags.
5. Set properties of `Source Record`
  - Configure recording path.
  - Set `Always` recording mode.
  - Wait 1 minute.
  - Set `Never` recording mode.
6. Check the recorded video file.

### Types of changes

- Bug fix (non-breaking change which fixes an issue)

- Code cleanup (non-breaking change which makes code smaller or more readable)

### CODE REVIEW

File: source-record.c [hunk 1]
```diff
@@ -227,6 +228,15 @@ static void source_record_filter_offscreen_render(void *data, uint32_t cx,
 	UNUSED_PARAMETER(cx);
 	UNUSED_PARAMETER(cy);
 	struct source_record_filter_context *filter = data;
+
+	uint64_t frame_time_ns = obs_get_video_frame_time();
+	int count = (int)((frame_time_ns - filter->last_frame_time_ns) /
+			  obs_get_frame_interval_ns());
+	filter->last_frame_time_ns = frame_time_ns;
```
Comment (norihiro) [inline source-record.c:235]: I put this line before other return conditions so that the `count` should not jump when starting to record.

**Comment by exeldro** [comment]
Thank you very much for this pull request. I knew there was something wrong with rendering lag. I will test and review it later today.
